hal: kernel: add missing preprocessor conditions for gpu3DMinClock
This fixes the following error when the kernel configuration is missing
'CONFIG_DEVICE_THERMAL' by adding the same condition on the '#if' as in the
block where the driver attr gpu3DMinClock is declared.

error: 'driver_attr_gpu3DMinClock' undeclared (first use in this function)

Signed-off-by: Stanislas Bach <sbach@0g.re>